CREATE TABLE IF NOT EXISTS stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar not null,
    uri varchar not null,
    ip varchar(15) not null,
    time_stamp timestamp without time zone not null,
    CONSTRAINT pk_stat PRIMARY KEY (id)
);