CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar not null,
    email varchar not null,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation text not null,
    category_id bigint not null,
    event_date timestamp without time zone not null,
    initiator bigint not null,
    paid boolean default false,
    title varchar not null,
    views bigint default 0,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id bigint not null,
    participant_id bigint not null,
    status varchar not null,
    CONSTRAINT pk_participation PRIMARY KEY (id),
    CONSTRAINT fk_participation_event_id FOREIGN KEY (event_id) REFERENCES event(id),
    CONSTRAINT fk_participation_participant_id FOREIGN KEY (participant_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS compilation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar(50) not null,
    pinned boolean default false,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event (
    compilation_id BIGINT NOT NULL REFERENCES compilation(id),
    event_id BIGINT NOT NULL REFERENCES event(id),
    CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id)
);